"""add parent_message_id

Revision ID: 007
Revises: 006
Create Date: 2026-07-09 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '007'
down_revision = '006_memory_embedding_index'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_messages', sa.Column('parent_message_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ai_messages_parent_message_id'), 'ai_messages', ['parent_message_id'], unique=False)
    op.create_foreign_key('fk_ai_messages_parent_message_id', 'ai_messages', 'ai_messages', ['parent_message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ai_messages_parent_message_id', 'ai_messages', type_='foreignkey')
    op.drop_index(op.f('ix_ai_messages_parent_message_id'), table_name='ai_messages')
    op.drop_column('ai_messages', 'parent_message_id')
    # ### end Alembic commands ###
